### ISSUE TITLE
Which OutputType in filename?

### ISSUE THREAD

**Issue by msingr** [msingr/csvGeom#18]
Suppose a csv-file contains several features. Some of them may be MultiPoint, some may be Point. Which suffix should be chosen for the filename?

**Comment by lsteinmann** [comment]
I would say point/polyline/polygon. It does not really matter to differentiate between the single/multi features for my use cases, as that covers the main difference of visual representation. The terminology difference between linestring/polyline is because of field desktop using polyline in the GUI, so users will recognize this one more then "linestring" - might consider changing that one in our GUI as well.

**Comment by msingr** [comment]
"Issue closed, as the chosen implementation already exists."
